**TASK:** import numpy

In [201]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [202]:
x = np.array([1,2,3])
print(x)

[1 2 3]


**TASK:** define (2 x 2) matrix 'A' 


In [203]:
A = np.array([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


**TASK:** define (2 x 2) matrix 'B'

In [204]:
B = np.array([[5,6], [7,8]])
B

array([[5, 6],
       [7, 8]])

**TASK:** check the type of 'x'

In [205]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [206]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [207]:
x.shape

(3,)

**TASK:** check the type of 'A'

In [208]:
type(A)

numpy.ndarray

**TASK:** 

In [209]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

"\nDefine function 'have_same_shape' which checks if two arrays have same shape.\n\nPARAMS:\n    array_1 (numpy.ndarray) - first array\n    array_2 (numpy.ndarray) - second array\nRETURN:\n    True - if arrays have same shape\n    False - if arrays do not have same shape\n\nAlso print 'Arrays must have same shape!' when returning False\n"

In [210]:
def have_same_shape(array_1, array_2):
    return array_1.shape == array_2.shape

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [211]:
have_same_shape(A, x)

False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [212]:
have_same_shape(A, B)

True

**TASK:** 

In [213]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


"\nDefine function 'matrix_addition' which perform matrix addition value by value.\n\nPARAMS:\n    A (numpy.ndarray) - first array\n    B (numpy.ndarray) - second array\nRETURN:\n    C (numpy.ndarray) - new A+B array\n\nIn this task do not consider broadcasting.\nDo not forget to check arrays shapes (you can use 'have_same_shape' function defined before)\n\n"

In [214]:
def matrix_addition(A, B):
    if have_same_shape(A,B):
        C = A + B
        return C
    else:
        return print("The two matrices do not have the same shape.")

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [215]:
matrix_addition(A, B)

array([[ 6,  8],
       [10, 12]])

**TASK:** 

In [216]:
"""
Define 'multiple_matrix_addition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_addition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [217]:
def multiple_matrix_addition(lst_of_arr):
    
    NEW_ARRAY = np.zeros_like(lst_of_arr[0])
    for i in range(len(lst_of_arr)):    
        NEW_ARRAY = matrix_addition(NEW_ARRAY, lst_of_arr[i])    
    return NEW_ARRAY

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [219]:
multiple_matrix_addition([A,A,B,B,B])

array([[17, 22],
       [27, 32]])

**TASK:** 

In [220]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

"\nDefine function 'can_multiply' that checks if two arrays (matrices) can be multiplied\n\nPARAMS:\n   array_a (numpy.ndarray) - first array\n   array_b (numpy.ndarray) - second array\nRETURN:\n    True - if arrays can be multiplied, also print the shape of the new array\n    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'\n    \n"

In [300]:
def can_multiply(array_a, array_b):
    if array_a.shape[1] == array_b.shape[0]:
        return True    
    print(False, '\nMatrices can not be multiplied.')

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [301]:
can_multiply(A, B)

True

**TASK:**  define matrix (3 x 2) matrix C

In [302]:
C = np.array([[1,2], [3,4], [5,6]])
print(C)

[[1 2]
 [3 4]
 [5 6]]


**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [303]:
can_multiply(A, C)

False 
Matrices can not be multiplied.


**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [304]:
can_multiply(C, A)

# Yes, because by switching their places, the function is now comparing the number of columns
# for C (which is 2) with number of rows of A (which is also 2).

True

**TASK:** 

In [305]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

"\nDefine function 'matrix_multiplication' that multiply two numpy.ndarrays\n\nPARAMS:\n   array_a (numpy.ndarray) - first array\n   array_b (numpy.ndarray) - second array\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new A * B array\n    \nDo not forget to check if two matrices can be multiplied.\n\n"

In [306]:
def matrix_multiplication(array_a, array_b):
    if can_multiply(array_a, array_b) == True:
        NEW_ARRAY = np.dot(array_a, array_b)
        return NEW_ARRAY

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [307]:
matrix_multiplication(C, B)

array([[19, 22],
       [43, 50],
       [67, 78]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [308]:
matrix_multiplication(A, C)

False 
Matrices can not be multiplied.
