# Basic Operations with Matrices

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [17]:
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
type(A)

numpy.ndarray

In [7]:
A.shape

(3, 2)

In [8]:
x.shape

(4,)

In [9]:
len(x)

4

## Transposition of a Matrix

In [12]:
A_T = A.T

In [13]:
A_T = A.transpose()

In [14]:
A_T. shape

(2, 3)

## Matrix Addition

In [15]:
B = np.array([[2, 5], [7, 4], [4, 3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [16]:
B.shape

(3, 2)

In [18]:
C = A + B

In [19]:
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

In [21]:
D = A + 1
D

array([[2, 3],
       [4, 5],
       [6, 7]])

## Matrix Multiplication

In [42]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
B = np.array([[2], [4]])
B

array([[2],
       [4]])

In [29]:
C = np.dot(A, B)
C

array([[10],
       [22],
       [34]])

In [30]:
C = A.dot(B)
C

array([[10],
       [22],
       [34]])

In [31]:
C.shape

(3, 1)

## Identity Matrices

In [34]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
IA = I.dot(A)
IA

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

## Determinant

In [47]:
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [49]:
det_M = np.linalg.det(M)
det_M

-2.0000000000000004

In [50]:
M = np.array([[1,2],[3,4],[5,6]])
det_M = np.linalg.det(M)
det_M

LinAlgError: Last 2 dimensions of the array must be square

## Inverse Matrices

In [60]:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [61]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [62]:
I = A_inv.dot(A)
I

array([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])