# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [3]:
null_array = np.zeros((10))
print(null_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
null_vector_10 = np.zeros((10))
null_vector_10[4] = 1
print(null_vector_10)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
vector = np.arange(0,5)
print(vector)
vector_reversed = vector[::-1]
print(vector_reversed)

[0 1 2 3 4]
[4 3 2 1 0]


#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
M =  np.arange(0, 9).reshape(3,3)
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
arr = [1,2,0,0,4,0]
print(np.nonzero(arr))

(array([0, 1, 4], dtype=int64),)


#### 8. Create a 3x3x3 array with random values (★☆☆)

In [11]:
arr = np.random.rand(3,3,3)
print(arr)

[[[0.93256824 0.81533645 0.3148983 ]
  [0.78083701 0.1760342  0.76045689]
  [0.21284767 0.4093964  0.20992818]]

 [[0.70742589 0.09831181 0.37043254]
  [0.91824914 0.71305032 0.54934062]
  [0.25856468 0.03697365 0.96882002]]

 [[0.74036357 0.8785568  0.79225921]
  [0.91214417 0.1615715  0.38838723]
  [0.01988094 0.76608019 0.38061225]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [18]:
arr = np.random.rand(10,10)
print(arr)
print('Mimimum value is', np.min(arr))
print('Maximum value is', np.max(arr))

[[0.55748931 0.75601037 0.7038017  0.02275814 0.11039454 0.28406832
  0.79866548 0.13087238 0.58517635 0.57799116]
 [0.1543071  0.70302534 0.24170281 0.74843468 0.09854601 0.22200842
  0.31869773 0.48202313 0.46077008 0.16568845]
 [0.80204636 0.61907791 0.34467422 0.23580628 0.28225089 0.05394121
  0.24431659 0.6103696  0.53621804 0.19598388]
 [0.18875551 0.75144077 0.23614148 0.66125479 0.71866733 0.44432163
  0.00261976 0.31243768 0.02373874 0.08862884]
 [0.72801683 0.83737727 0.22882836 0.6983895  0.53603648 0.46829612
  0.31473031 0.31800043 0.93185915 0.02187962]
 [0.11826806 0.83188786 0.35238243 0.6293036  0.75194083 0.243504
  0.53526599 0.89793649 0.83233791 0.98590865]
 [0.88301931 0.9817313  0.74429068 0.14783471 0.86192781 0.51631856
  0.31432489 0.43272325 0.23612009 0.04836184]
 [0.86375502 0.63630315 0.27144282 0.75595771 0.71287053 0.94894611
  0.71421534 0.9771729  0.76268822 0.11638525]
 [0.42073795 0.35217772 0.05812183 0.84979474 0.57360289 0.3985954
  0.31764357 0.

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [19]:
arr = np.random.rand(30)
print(arr)
print('The mean value is', np.mean(arr))

[0.38183207 0.4539344  0.98988556 0.83813827 0.66839584 0.5134236
 0.3376764  0.10454131 0.62280345 0.70246769 0.81164366 0.31487123
 0.29187894 0.84992348 0.85110698 0.4555819  0.1783792  0.07393477
 0.79037466 0.68303534 0.3254532  0.02421812 0.05263248 0.4218221
 0.71579965 0.86420139 0.73834471 0.10220958 0.5697158  0.48159532]
The mean value is 0.5069940364572568


#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [29]:
arr = np.ones([4,4])
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [35]:
arr = np.ones([4,4])
print(arr)
print('This is the new array:')
arr = np.pad(arr, pad_width = 1, mode = 'constant', constant_values = 0)
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
This is the new array:
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [48]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

# The result is False

False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [136]:
a = np.diag(np.array([1, 2, 3, 4]), k = -1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [43]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 16. Normalize a 5x5 random matrix (★☆☆)

In [218]:
arr = np.random.randint(0,10, size = (5,5))
amax, amin = arr.max(), arr.min()
arr= (arr-amin)/(amax-amin)
print(arr)

[[0.875 0.875 0.375 0.125 0.875]
 [0.375 0.5   0.25  0.125 1.   ]
 [0.25  0.    0.5   0.75  1.   ]
 [0.5   0.    0.875 1.    0.25 ]
 [1.    0.625 0.75  0.5   0.875]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [50]:
arr = np.arange(10)
print(arr)
arr[(3 < arr) & (arr < 8)] *= -1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 18. How to round away from zero a float array ? (★☆☆)

In [223]:
arr = np.random.random((5))
print(arr)
print(np.round(arr,0))

[0.52003465 0.69964161 0.99369542 0.07022404 0.03931358]
[1. 1. 1. 0. 0.]


#### 19. Find common values between two arrays? (★☆☆)

In [244]:
arr_A = np.array([1, 2, 3, 4, 5])
print("Array1: ",arr_A)
arr_B = [4,3,2,1]
print("Array2: ",arr_B)
print("Common values between two arrays:")
print(np.intersect1d(arr_A, arr_B))

Array1:  [1 2 3 4 5]
Array2:  [4, 3, 2, 1]
Common values between two arrays:
[1 2 3 4]


#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [230]:
np.sqrt(-1) == np.emath.sqrt(-1)

# They should return the same value but they are handled diferently
# by these two functions and thus returns False.

<ipython-input-230-12d214f2d6d3>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [55]:
def generator(): 
    for i in range(10):
        yield i

arr = np.fromiter(generator(), dtype=float, count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [108]:
a = np.linspace(0, 1, 12, endpoint = True)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 23. Create a random vector of size 10 and sort it (★★☆)

In [126]:
a = np.random.rand(10)
a.sort()
print(a)

[0.07826695 0.08749206 0.1060968  0.12428546 0.25562658 0.31193747
 0.34899469 0.39453873 0.50402923 0.8232223 ]


#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [184]:
A = np.random.randint(0,2,size = 5)
B = np.random.randint(0,2,size = 5)
print(np.allclose(A,B))

False


#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [37]:
arr = np.random.randint(0, 10, size = 10)
print(arr)
print(np.argmax(arr))
arr[arr.argmax()] = 0
print(arr)

[1 8 5 5 2 5 0 0 8 5]
1
[1 0 5 5 2 5 0 0 8 5]


#### 26. Find the closest value to random element in a vector? (★★☆)

In [66]:
arr = np.arange(0, 50)
print('Array:', arr)
random = np.random.uniform(0, 50)
print('Random number:', random)
index = (np.abs(arr - random)).argmin()
print('The closest value is:', arr[index])

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Random number: 29.427060317766653
The closest value is: 29


#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [56]:
arr = np.array([9.0, 8.0, 7.0], dtype = 'int32')
print(arr)

[9 8 7]


#### 28. Sort an array by the nth column? (★★☆)

In [165]:
arr = np.random.randint(0,5,(3,3))
print(arr)
print(arr[arr[:,-1].argsort()])

[[3 0 4]
 [0 4 2]
 [4 3 3]]
[[0 4 2]
 [4 3 3]
 [3 0 4]]


#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [118]:
arr = np.random.randint(0,3, size = (3,3))
print(arr)
print((~arr.any(axis=0)).any())

[[0 2 2]
 [0 0 1]
 [1 2 2]]
False


#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [234]:
vec = np.array([1,2,3,4,5])
n_vec = 3
vec_0 = np.zeros(len(vec) + (len(vec)-1)*(n_vec))
vec_0[::n_vec+1] = vec
print(vec_0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 31. Swap two rows of an array? (★★★)

In [237]:
arr = np.arange(25).reshape(5,5)
print(arr)
arr[[0,1]] = arr[[1,0]]
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 32. How to negate a boolean value inside an array? (★★★)

In [7]:
arr_bool = np.array([True, False, 1, 0])
print(arr_bool)
print(np.logical_not(arr_bool))



[1 0 1 0]
[False  True False  True]


#### 33. Find the most frequent value in an array?

In [256]:
a = np.random.randint(0,10,50)
print(a)
print(np.bincount(a).argmax())

[4 1 6 9 2 1 8 5 8 3 8 7 2 4 1 8 8 4 3 4 1 6 7 7 6 4 1 0 5 9 0 2 8 1 2 8 8
 3 0 8 2 5 7 6 6 4 7 3 9 4]
8


#### 34. Get the n largest values of an array (★★★)

In [52]:
arr = np.arange(10000)
np.random.shuffle(arr)
n = 5

# Slow
print (arr[np.argsort(arr)[-n:]])

# Fast
print (arr[np.argpartition(-arr,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9996 9998 9997 9995]


#### 35. Extract unique rows from a two dimensional array? (★★★)

In [16]:
arr = np.array([[1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 1, 0],         
       [0, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0]])

arr_unique = np.unique(arr, axis = 0)
print(arr_unique)

[[0 1 1 1 0 0]
 [0 1 1 1 1 0]
 [1 1 1 0 0 0]
 [1 1 1 1 1 0]]
