In [1]:
#### Python Lists vs Numpy Arrays - What is the difference?

In [21]:
import time
import numpy as np

size_of_vec = 1000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1


t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")


0.0 0.0


ZeroDivisionError: float division by zero

In [20]:
import numpy as np
from timeit import Timer

size_of_vec = 1000
X_list = range(size_of_vec)
Y_list = range(size_of_vec)
X = np.arange(size_of_vec)
Y = np.arange(size_of_vec)

def pure_python_version():
    Z = [X_list[i] + Y_list[i] for i in range(len(X_list)) ]

def numpy_version():
    Z = X + Y

timer_obj1 = Timer("pure_python_version()", 
                   "from __main__ import pure_python_version")
timer_obj2 = Timer("numpy_version()", 
                   "from __main__ import numpy_version")

print(timer_obj1.timeit(10))
print(timer_obj2.timeit(10))  # Runs Faster!

print(timer_obj1.repeat(repeat=3, number=10))
print(timer_obj2.repeat(repeat=3, number=10)) # repeat to prove it!



0.0032527999999842905
0.0005373999999847001
[0.0026227000000176304, 0.00287279999997736, 0.004089599999986149]
[0.0007185999999705928, 0.00013119999999844367, 0.0008704999999622487]


In [23]:
#### Python NumPy Tutorial for Beginners
#### Source: https://www.youtube.com/watch?v=QUT1VHiLmmI

In [31]:
import numpy as np

In [32]:
a = np.array([1,3,5])
b = np.array([1,2,3])

In [33]:
print(a)
print(b)

[1 3 5]
[1 2 3]


In [34]:
a * b

array([ 1,  6, 15])

In [35]:
#### The Basics

In [50]:
a = np.array([1,2,3], dtype = 'int32')
print(a)

[1 2 3]


In [41]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [42]:
# Get Dimension
a.ndim

1

In [43]:
b.ndim

2

In [44]:
# Get Shape
a.shape

(3,)

In [45]:
b.shape

(2, 3)

In [51]:
# Get Type
a.dtype

dtype('int32')

In [58]:
# Get Size
a.itemsize
b.itemsize

8

In [59]:
# Get total size
a.size * a.itemsize

12

In [60]:
a.nbytes

12

In [61]:
#### Accessing/Changing specific elements, rows, columns, etc

In [63]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [64]:
a.shape

(2, 7)

In [68]:
# Get a specific element [r, c]
a[1, 5]

13

In [69]:
a[1, -2]

13

In [70]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [71]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [76]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [78]:
a[1, 5] = 20

In [79]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [80]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [81]:
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [89]:
# 3-D Example
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [90]:
# Get specific element (work outside in)
b[0,1,1]

4

In [91]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [92]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [94]:
b[0,1,1]

4

In [96]:
# Replace
b[:,1,:] = [[9,9], [8,8]]

In [97]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [98]:
#### Initializing Different Types of Arrays

In [100]:
# All 0s matrix

In [119]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [120]:
# All 1s matrix

In [124]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [130]:
# Any othernumber
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [131]:
# Any other number (full_like)

In [133]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [134]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [136]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.23801372, 0.70055092, 0.68098923],
        [0.82349411, 0.24395294, 0.01688526]],

       [[0.98235372, 0.26577984, 0.65204362],
        [0.36402898, 0.52550874, 0.38311448]],

       [[0.44511483, 0.78925909, 0.71721123],
        [0.38711898, 0.7828848 , 0.15141523]],

       [[0.6067872 , 0.66806369, 0.39215528],
        [0.64407646, 0.08968132, 0.91518455]]])

In [137]:
np.random.random_sample(a.shape)

array([[0.55897352, 0.3234957 , 0.78706206, 0.34923615, 0.12975583,
        0.59478631, 0.66422244],
       [0.28263109, 0.61700642, 0.77247344, 0.75793341, 0.77640047,
        0.62057651, 0.07725672]])

In [138]:
np.random.rand(4,2)

array([[0.58830766, 0.84675661],
       [0.22329109, 0.29696842],
       [0.48881363, 0.20532511],
       [0.09865027, 0.403801  ]])

In [279]:
# Random integer values
np.random.randint(-4,8, size=(3,3))

array([[ 0,  0,  4],
       [-1, -3,  2],
       [ 0, -4,  5]])

In [281]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [282]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [300]:
# Repeat an array
arr = np.array([[1,2,3]])

In [301]:
r1 = np.repeat(arr, 3, axis = 0)

In [302]:
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [313]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [318]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


In [319]:
#### Mathematics

In [339]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [333]:
a + 2

array([3, 4, 5, 6])

In [334]:
a - 2

array([-1,  0,  1,  2])

In [335]:
a * 2

array([2, 4, 6, 8])

In [336]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [337]:
a += 2
a

array([3, 4, 5, 6])

In [340]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [341]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [344]:
# Take the sin and cos
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [343]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [345]:
#### Linear Algebra

In [347]:
a = np.full((2,3), 1)
print(a)

b = np.full((3,2), 2)
print(b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


In [349]:
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [352]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [353]:
#### Statistics

In [357]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [363]:
np.min(stats)

1

In [365]:
np.max(stats, axis = 1)

array([3, 6])

In [371]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [372]:
#### Reorganizing Arrays

In [373]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [374]:
print(before.shape)

(2, 4)


In [378]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [393]:
# Vertically stacking vectors

In [380]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [383]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [394]:
# Horizontal stacks

In [391]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print(h2)

np.hstack([h1,h2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [392]:
#### Miscellaneous

In [400]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata.astype('int32')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [402]:
# Boolean Masking and Advanced Indexing

In [403]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [404]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [405]:
# You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [408]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [409]:
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [410]:
np.any(filedata > 50, axis = 1)

array([ True,  True,  True])

In [411]:
np.all(filedata > 50, axis = 1)

array([False, False, False])

In [414]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])